### ISSUE TITLE
How can i test different high-pixel-density properties for Desktop ?

### ISSUE THREAD

**Issue by dannypk** [CHECK24/howcani#8]
On desktop, i cannot test the high-pixel-density properties which means i cannot test the properties for retina and non retina images.
On mobile,  iphone 6 for example is high-pixel-density and it uses retina, nokia lumia 520 is the normal, no retina.

**Comment by Heimschmiede** [comment]
I tested it by making high density always run (commenting out lines in the less file). Due to transformations the result should look the same on your local desktop. 
You can also use our mobile phones to vist the web page running on your local machine.

**Comment by janbaer** [comment]
How about the Chrome developer tools? There you can define if you have a high density device or not.

**Comment by Heimschmiede** [comment]
@Jan: I had the feeling that the density was not working when using device settings in the dev tools but the documentation says that the device pixel ratio is also set. So it should work using the chrome dev tools.
see https://developers.google.com/web/tools/chrome-devtools/iterate/device-mode/emulate-mobile-viewports

**Comment by chrgruber** [comment]
Dev tools don't seem to work at least for our pages

**Comment by dannypk** [comment]
The devices is not a problem. Lumia 520 is non-retina, all the others (iPhones) are retina. The problem is for desktop. With our monitors, we have retina images. With Macs 5k, there should be retina3. What about the normal images? Which resolution should have normal images ? How can we emulate a non-retina display, not as a device, but as desktop ?

**Comment by Heimschmiede** [comment]
Did you try to add a custom device in the chrome dev tools: The the device-dropdown there is an option "Edit..." where you can add a custom setting with a given DPI.

**Comment by dannypk** [comment]
Ow .. actually you are right. I thought that as "devices" i can add only mobile / tablets. I could add a "desktop" version with pixel density of 1.6 and there it was the retina. nice :) gg google.

**Comment by jan** [comment]
@Heimschmiede: Also worth a read: "How can I not summon @Jan to this discussion instead of @janbaer?" :P
